import Link from "next/link";
import { getSegmentFromCookie } from "@/lib/cookies";
import { ScenarioExplanation } from "@/app/components/ScenarioExplanation";
import { StaticBuildTimeBlock } from "@/app/components/StaticBuildTimeBlock";
import { SegmentDataBlock } from "./SegmentDataBlock";

export default async function Scenario4Page() {
  const segment = await getSegmentFromCookie();

  return (
    <div className="space-y-8">
      <div>
        <Link href="/" className="text-sm text-indigo-400 hover:underline">
          ← Back
        </Link>
        <h1 className="mt-2 text-2xl font-bold text-white">
          Scenario 4: Middleware + Server Component hybrid
        </h1>
        <p className="mt-1 text-zinc-400">
          Middleware could set the segment; this page is a static shell. The block below is a Server
          Component that reads the segment (cookie) and fetches segment-based data. Next.js data
          cache can be configured per segment; the response is still from origin (not CDN-cached).
        </p>
      </div>

      <StaticBuildTimeBlock />

      <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
        <h2 className="text-sm font-medium uppercase tracking-wider text-zinc-500">
          Segment-based data (RSC, segment from cookie)
        </h2>
        <SegmentDataBlock segment={segment} />
      </div>

      <ScenarioExplanation
        title="How this scenario works"
        middlewareUsed={true}
        contentServedFromCdn={false}
        contentServedFromCdnNote="RSC fetches per request; Next.js data cache per segment does not make the response CDN-cached"
        secondRequestFromCache={false}
        secondRequestFromCacheNote="response is server-rendered every time; Next.js data cache does not cache the response at CDN"
        steps={[
          "Middleware can run first to set or read segment (e.g. from cookie or header); in this demo we read segment in the page.",
          "Page shell is static; the route is not rewritten. Middleware may set cookies used later.",
          "Page loads as a Server Component. It reads the segment from cookies (e.g. personalisation-segment).",
          "A Server Component (SegmentDataBlock) fetches or computes segment-specific data (e.g. different features per segment).",
          "Next.js data cache can be configured per segment (e.g. fetch cache key or unstable_cache with segment); each segment can have its own cached data. The full page response is still generated by the server and is not CDN-cached.",
          "Result: static shell plus server-rendered, segment-specific sections. Response always from origin.",
          "Second request (same user/segment): No — the RSC runs again and the response is not served from CDN. Next.js data cache (e.g. fetch or unstable_cache with segment key) can avoid refetching data on the server, but the HTTP response is still generated by the server each time, so no CDN caching of the response.",
        ]}
        vercelUsage={[
          "If middleware is used: 1 Edge Middleware invocation per request.",
          "Every page view = 1 Serverless Function invocation (RSC reads segment, fetches data).",
          "Bandwidth: full response from origin on every request (Next.js data cache does not cache the response at CDN).",
          "Similar to Scenario 1 in usage; middleware adds a small amount of edge compute.",
        ]}
      />
    </div>
  );
}
