import Link from "next/link";
import { Suspense } from "react";
import { ScenarioExplanation } from "@/app/components/ScenarioExplanation";
import { StaticBuildTimeBlock } from "@/app/components/StaticBuildTimeBlock";
import { Scenario4DynamicContent } from "./Scenario4DynamicContent";

function Placeholder() {
  return (
    <div className="mt-3 rounded-lg border border-dashed border-zinc-600 p-4 text-zinc-500">
      Loading…
    </div>
  );
}

export default function Scenario4Page() {
  return (
    <div className="space-y-8">
      <div>
        <Link href="/" className="text-sm text-indigo-400 hover:underline">
          ← Back
        </Link>
        <h1 className="mt-2 text-2xl font-bold text-white">
          Scenario 4: Middleware + Server Component hybrid
        </h1>
        <p className="mt-1 text-zinc-400">
          User context (segment, personalised components) comes from Salesforce (mock). The block
          below is a Server Component that uses segment-based data. Next.js data cache can be
          configured per segment; the response is still from origin (not CDN-cached).
        </p>
      </div>

      <StaticBuildTimeBlock />

      <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
        <h2 className="text-sm font-medium uppercase tracking-wider text-zinc-500">
          Segment-based data (RSC, segment from Salesforce)
        </h2>
        <Suspense fallback={<Placeholder />}>
          <Scenario4DynamicContent />
        </Suspense>
      </div>

      <ScenarioExplanation
        title="How this scenario works"
        middlewareUsed={true}
        contentServedFromCdn={false}
        contentServedFromCdnNote="RSC fetches per request; Next.js data cache per segment does not make the response CDN-cached"
        secondRequestFromCache={false}
        secondRequestFromCacheNote="response is server-rendered every time; Next.js data cache does not cache the response at CDN"
        steps={[
          "Page loads as a Server Component. Server reads user email from cookies and fetches user context from Salesforce (mock: segment, personalised component IDs).",
          "If this component is in the user's personalisedComponentIds, SegmentDataBlock receives the segment from Salesforce and fetches or computes segment-specific data.",
          "Next.js data cache can be configured per segment (e.g. unstable_cache with segment key); each segment can have its own cached data. The full page response is still generated by the server and is not CDN-cached.",
          "Result: static shell plus server-rendered, segment-specific sections driven by Salesforce context. Response always from origin.",
          "Second request (same user): No — the RSC runs again and the response is not served from CDN. Data cache can avoid refetching Salesforce/segment data on the server, but the HTTP response is still generated each time.",
        ]}
        vercelUsage={[
          "Every page view = 1 Serverless Function invocation (RSC fetches Salesforce user context, then segment data).",
          "Bandwidth: full response from origin on every request (Next.js data cache does not cache the response at CDN).",
          "Similar to Scenario 1 in usage; Salesforce user context is the source of truth for segment and which components to personalise.",
        ]}
      />
    </div>
  );
}
